project:
  type: website

website:
  title: "Ivan U. Ricardo"
  navbar:
    background: "#2d3561"
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Posts
        href: posts.qmd
    tools:
      - icon: github
        href: https://github.com/ivanuricardo
        menu:
          - text: Source Code
            url:
          - text: Report a Bug
            url:
      - icon: linkedin
        href: https://www.linkedin.com/in/ivanuricardo/
  cookie-consent:
    type: express
    style: simple

  page-footer: "Made with ❤️, Copywrite 2024, Ivan U. Ricardo"
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



